import { Role } from "src/app/core/models/role";
import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MANAGEMENT_SYSTEM.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Management System Modules
  {
    path: "/extra-pages/blank",
    title: "MENUITEMS.CALENDAR.TEXT",
    moduleName: "scheduling",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  {
    path: "/patient",
    title: "MENUITEMS.PATIENTS.TEXT",
    moduleName: "patients",
    iconType: "material-icons-two-tone",
    icon: "face",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  {
    path: "/contact",
    title: "MENUITEMS.CONTACTS.TEXT",
    moduleName: "contacts",
    iconType: "material-icons-two-tone",
    icon: "contacts",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  {
    path: "/locations",
    title: "MENUITEMS.LOCATIONS.TEXT",
    moduleName: "locations",
    iconType: "material-icons-two-tone",
    icon: "map",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },
  
  // Administration
  {
    path: "",
    title: "MENUITEMS.ADMINISTRATION.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Administration Modules
  {
    path: "/administration/employee",
    title: "MENUITEMS.EMPLOYEES.TEXT",
     moduleName: "employees",
    iconType: "material-icons-two-tone",
    icon: "people_alt",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  {
    path: "/blank",
    title: "MENUITEMS.VEHICLES.TEXT",
     moduleName: "vehicles",
    iconType: "material-icons-two-tone",
    icon: "airport_shuttle",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },
  
  // Accounting
  {
    path: "",
    title: "MENUITEMS.ACCOUNTING.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Accounting Modules
  {
    path: "/blank",
    title: "MENUITEMS.ACCOUNTING.TEXT",
     moduleName: "accounting",
    iconType: "material-icons-two-tone",
    icon: "description",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  {
    path: "/blank",
    title: "MENUITEMS.CONTRACTS.TEXT",
     moduleName: "contracts",
    iconType: "material-icons-two-tone",
    icon: "description",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },
  
  {
    path: "/blank",
    title: "MENUITEMS.PRODUCTS.TEXT",
     moduleName: "products",
    iconType: "material-icons-two-tone",
    icon: "description",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Controlling
  {
    path: "",
    title: "MENUITEMS.CONTROLLING.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Applications
  {
    path: "",
    title: "MENUITEMS.APPLICATIONS.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Search
  {
    path: "",
    title: "MENUITEMS.SEARCH.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

    // Logopedic Practice Management
  {
    path: "",
    title: "MENUITEMS.PRACTICE_MANAGEMENT.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: [Role.ADMINISTRATOR, Role.SUPER_ADMINISTRATOR],
    submenu: [],
  },
  {
    path: "/practice-management",
    title: "MENUITEMS.PRACTICE_MANAGEMENT.TEXT",
    moduleName: "",
    iconType: "material-icons-two-tone",
    icon: "account_balance",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [Role.ADMINISTRATOR, Role.SUPER_ADMINISTRATOR],
    submenu: [],
  },


];
