export enum Role {
  All = 'All',
  SUPER_ADMINISTRATOR = 'SUPER_ADMINISTRATOR',
  ADMINISTRATOR = 'ADMINISTRATOR',
  PRACTICE_MANAGER = 'PRACTICE_MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  PATIENT = 'PATIENT',
}
